### ISSUE TITLE
Add shorDescription and LongDescription to Parameter in parser code

### ISSUE THREAD

**Issue by tech3371** [medley56/space_packet_parser#14]
# Summary
get shortDescription  or LongDescription from XTCE definition and reference in unpacked data.

In XTCE definition xml file, it will look like this
```
            <xtce:Parameter name="SPIN_PERIOD_SOURCE" parameterTypeRef="spin_period_source_enum">
                <xtce:LongDescription>
                Spin period source bit:
                '1' -- sun sensor (safing),
                '0' -- star tracker (nominal)
            </xtce:LongDescription>
            </xtce:Parameter>
```
In python code, it will reference it like this
```
Eg.
value = packet.data["SPIN_PERIOD_SOURCE"].raw_value and description = packet.data["IDX__TXHDREVTNUM"].LongDescription
```

**Comment by tech3371** [comment]
Notes from @medley56

to add logic to the XTCE parsing code to actually look at those fields, follow these steps:
1. While parsing each Parameter (in the XTCE document), search for short and long description elements (pass if not present or malformed).
2. If short or long description is present, store that information in an internal instance attribute such that they can be looked up by Parameter name.
3. Create getter methods for those internal instance attributes to look up descriptions by parameter name.

**Comment by medley56** [comment]
@bryan-harter or @tech3371 I'm sorry I haven't gotten around to implementing this. I encourage you to take a stab though if you have time. It's only adding functionality to the XTCE parser and bookkeeping the description information as key value pairs.
