### ISSUE TITLE
Add example of variable length field calculations to documentation

### ISSUE THREAD

**Issue by medley56** [medley56/space_packet_parser#35]
When defining a variable length field in XTCE that just takes up "the rest of the packet", people often run into questions surrounding the PKT_LEN field in the header (counts from zero and does not include CCSDS header) and how to define the dynamic size for that parameter type. 

Include an example of this XTCE in the documentation.

**Comment by tech3371** [comment]
This would be very helpful. Talking about more documentation, do you have any advice on how to develop and test development in this repo locally?

**Comment by medley56** [comment]
@tech3371 We use the standard open source workflow so there's nothing special to know. You are listed as a collaborator so you should be able to directly make branches from this remote. Alternatively, you can fork the repo and make your branch there - anyone can do this regardless of collaborator status. Regardless, to link a branch to an issue, use the "Create a branch" button on the RHS of the issue page, under the "Development" heading and then choose the correct repo in which to make the branch (could either be this repo or your fork of it).

**Comment by greglucas** [comment]
This was fixed in #50. Thanks @laspsandoval!
