### ISSUE TITLE
Disposition CSV-based packet definition code

### ISSUE THREAD

**Issue by medley56** [medley56/space_packet_parser#40]
There is some old CSV-based packet definition code that has not been worked on in a long time. This code works fundamentally differently from the XTCE code and the functionality is much more limited. 

Specific issues that need attention:
1. Documentation of CSV format supported by the CsvPacketDefinition class.
2. Improved unit tests for CSV-based packet parsing.
3. Separation of concerns between CSV-based parsing and XtcePacketDefinition. There are currently deprecated methods in XtcePacketDefinition that are only there in order to prevent breakage of the CSV-based parser. 

We can either take the action to make these updates or we can just remove the CSV parsing from the package. I'd rather do the former because I want to support projects that can't/won't generate XTCE.

**Comment by greglucas** [comment]
For the CSV-based parsing, I see there is a "flattened_containers" holding everything, it has `entry_list` and `restriction_criteria` the same as the `xtcedef.SequenceContainer`. Would it be possible to pass those to `SequenceContainer()`, and make one "empty" root container to hold all of them instead? It would still be flat, but this way it would parse with the same logic as the current SequenceContainer version does, it just only ever goes one level deep.

This would be a way to get rid of the legacy parser code, but keep the CSV definitions.
